version: '3'

services:
  postgres-db:
    image: 'postgres:13'
    container_name: 'drone-db-postgres'
    environment:
      - 'POSTGRES_USER=compose-postgres'
      - 'POSTGRES_PASSWORD=compose-password'
      - 'POSTGRES_DB=drones_db'

  app:
    build: ./
    container_name: 'drone-app-java'
    depends_on:
      - postgres-db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/drones_db
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-password